kettclub/administration/urls.py
from django.conf.urls import url

from kettclub.administration.views import dash, Logout, Login

urlpatterns = [
    url(r'^login/', Login, name='login'),
    url(r'^logout/', Logout, name='logout'),
    url(r'^$', dash, name='dash'),
]

kettclub/config/urls.py
from django.conf.urls import url
from kettclub.config.view_config import configuracao
from kettclub.config.view_utilizadores import listUsers, fichaUser, resetPassword, desativarUsers, \
    confirmDesativarUsers, \
    ativarUsers, confirmAtivarUsers, success, addUser, editUser, listGrupos, addGrupo, meuPerfil, fichaMeuPerfil, \
    editGrupo, fichaGrupo, confirmApagarGrupos, apagarGrupo

urlpatterns = [
    url(r'^sucesso/', success, name='success'),

    # Menu Configuração
    url(r'^$', configuracao, name="config"),

    # Listagem Utilizadores
    url(r'^users/$', listUsers, name="listUsers"),

    # Criar Utilizador
    url(r'^users/add/$', addUser, name="addUser"),

    # Editar Utilizador
    url(r'^users/edit/(?P<idUser>\d+)/$', editUser, name="editUser"),

    # Ficha Utilizador
    url(r'^users/view/(?P<idUser>\d+)/$', fichaUser, name="fichaUser"),

    # Desativar Utilizador
    url(r'^users/des/confirm/(?P<listUsers>\w+)/$', desativarUsers,
        name="desativarUsers"),

    # Confirmar Desativar Utilizador
    url(r'^users/des/confirm/$', confirmDesativarUsers,
        name="confirmDesativarUsers"),

    # Ativar Utilizador
    url(r'^users/act/confirm/(?P<listUsers>\w+)/$', ativarUsers,
        name="ativarUsers"),

    # Confirmar Ativar Utilizador
    url(r'^users/act/confirm/$', confirmAtivarUsers,
        name="confirmAtivarUsers"),

    # Ativar Utilizador
    url(r'^users/reset/pwd/(?P<idUser>\d+)/$', resetPassword,
        name="resetPassword"),

    # Listagem de Grupos de Utilizador
    url(r'^users/grupo/$', listGrupos, name="listGrupos"),

    # Criar Grupo de Utilizadores
    url(r'^users/grupo/add/$', addGrupo, name="addGrupo"),

    # Editar Grupo de Utilizador
    url(r'^users/grupo/edit/(?P<idGroup>\d+)/$', editGrupo,
        name="editGrupo"),

    # Ficha Grupo de Utilizador
    url(r'^users/grupo/view/(?P<idGroup>\d+)/$', fichaGrupo,
        name="fichaGrupo"),

    # Apagar Grupo
    url(r'^users/grupo/del/confirm/(?P<listGrupos>\w+)/$', apagarGrupo,
        name="apagarGrupo"),

    # Confirmar Apagar Grupo
    url(r'^users/grupo/del/confirm/$', confirmApagarGrupos,
        name="confirmApagarGrupos"),

    # Meu Perfil
    url(r'^settings/perfil/(?P<idUser>\d+)/$', meuPerfil, name="meuPerfil"),

    # Ficha Meu Perfil
    url(r'^settings/perfil/view/(?P<idUser>\d+)/$', fichaMeuPerfil,
        name="fichaMeuPerfil"),

]

kettclub/monthlyplans/urls.py
from django.conf.urls import url
from kettclub.monthlyplans.views import new, editPlano, delDataModalPlano, \
    delConfirmePlano, listmonthlyplan, success, activeDataModalSubscription, activeConfirmeSubscription

urlpatterns = [
    url(r'^$', new, name='new'),
    url(r'^edit/(?P<pk>\d+)$', editPlano, name="edit"),
    url(r'^lista/', listmonthlyplan, name='list'),
    url(r'^deletar/', delDataModalPlano, name='delete'),
    url(r'^ativar/', activeDataModalSubscription, name='activate'),
    url(r'^confirmedeletar/', delConfirmePlano, name='delconfirme'),
    url(r'^confirmeativar/', activeConfirmeSubscription, name='activeconfirm'),
    url(r'^sucesso/', success, name='success'),
]

kettclub/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from kettclub.administration.views import Logout, Login
from kettclub.core.views import home, unauthorized
from kettclub.exercises.api import views as exercises_api_views
admin.site.site_header = 'Administração Kettclub'

urlpatterns = [
    url(r'^$', home.as_view(), name='home'),
    # url(r'^sucesso/', success.as_view(), name='success'),
    url(r'^naoautorizada/', unauthorized.as_view(), name='redirect'),

    url(r'^administracao/', include('kettclub.administration.urls',
                                namespace='administration')),
    url(r'^login/', Login, name='login'),

    url(r'^logout/$', Logout, name='logout'),
    # url(r'^novo/', include('kettclub.subscriptions.urls',
    #                             namespace='subscriptions')),
    url(r'^inscricao/', include('kettclub.subscriptions.urls',
                                namespace='subscriptions')),
    url(r'^inscricaoexterna/', include('kettclub.externalapplication.urls',
                                namespace='external')),
    url(r'^presenca/', include('kettclub.assiduousness.urls',
                               namespace='assiduousness')),
    url(r'^avaliacaofisica/', include('kettclub.reviewsphysicals.urls',
                                      namespace='reviewsphysicals')),
    url(r'^planosmensais/', include('kettclub.monthlyplans.urls',
                                      namespace='monthlyplans')),
    url(r'^saudeanamnese/', include('kettclub.healthanamnese.urls',
                                    namespace='healthanamnese')),
    url(r'^config/', include('kettclub.config.urls',
                                    namespace='config')),
    url(r'^exercise/', include('kettclub.exercises.urls', namespace="exercise")),
    url(r'^api/v2/exercise/search/$',
        exercises_api_views.search,
        name='exercise-search'),
    url(r'^admin/', admin.site.urls),
]

kettclub/core/models.py
from django.db import models

kettclub/core/forms.py
from django import forms
from django.core.exceptions import ValidationError


class EmailForm(forms.Form):
    name = forms.CharField(label='Nome', widget=forms.TextInput(
        attrs={'placeholder': 'Nome', 'class': 'form-control'}))
    email = forms.EmailField(label='Email', widget=forms.TextInput(
        attrs={'placeholder': 'Email', 'class': 'form-control'}))
    phone = forms.CharField(label='Telefone', required=False, widget=forms.TextInput(
        attrs={'placeholder': 'Telefone', 'class': 'form-control'}))
    message = forms.CharField(label='Mensagem', widget=forms.Textarea(
        attrs={'placeholder': 'Mensagem', 'class': 'form-control', 'rows': '5'}))

    def clean_name(self):
        name = self.cleaned_data['name']
        words = [w.capitalize() for w in name.split()]
        return ' '.join(words)

    def clean(self):
        self.cleaned_data = super().clean()
        if not self.cleaned_data.get('email') and not self.cleaned_data.get('phone'):
            raise ValidationError('Informe seu e-mail ou telefone.')

        return self.cleaned_data



# class EmailForm(forms.ModelForm):
#     class Meta:
#         model = Email
#         fields = ['name', 'email', 'phone', 'message']
#
#     def clean_name(self):
#         name = self.cleaned_data['name']
#         words = [w.capitalize() for w in name.split()]
#         return ' '.join(words)
#
#     def clean(self):
#         self.cleaned_data = super().clean()
#         if not self.cleaned_data.get('email') and not self.cleaned_data.get('phone'):
#             raise ValidationError('Informe seu e-mail ou telefone.')
#
#         return self.cleaned_data

kettclub/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from kettclub.administration.forms import LoginForm


class home(TemplateView):
    template_name ='home.html'


# def home(request):
#     return render(request, 'home.html', {'form': LoginForm})

# class success(TemplateView):
#     template_name = 'success.html'


# def success(request):
#     return render(request, 'success.html')


class unauthorized(TemplateView):
    template_name = 'pagina_nao_autorizada.html'

# def unauthorized(request):
#     return render(request, 'pagina_nao_autorizada.html')

kettclub/core/templates/home.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="pt">

{% block content %}






    <section id="subscription" style="padding-top: 200px;">
        <body id="page-top" class="form_id index  panel box-v1">
        <!-- Header -->
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">

                        <img class="img-responsive" src="{% static 'img/banner.jpg' %}" alt="">

                        {#                        <div class="intro-text">#}
                        {#                            <span class="name">Functional Training</span>#}
                        {#                            <hr class="star-primary">#}
                        {#                            <span class="skills">Ginásio de treino funcional</span>#}
                        {#                        </div>#}
                    </div>
                </div>
            </div>
        </header>
        <!-- Subscribe Section -->
        <section class="subsctiption" id="about" style="padding-top: 50px;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        {#                    <div>#}
                        <h2>Marcação de presença</h2>
                        {#                        <hr class="star-primary">#}
                        {#                        <div class="intro-text">#}
                        {#                            <span class="skills">Lista de assiduidade</span>#}
                        {#                        </div>#}
                        <a href="{% url 'assiduousness:new' %}" class="portfolio-link" data-toggle="modal">
                            <div class="caption">
                                <div class="caption-content">
                                    <button type="submit" class="btn btn-primary">Presença</button>
                                    {#                                    <i class="fa fa-search-plus fa-3x"></i>#}
                                </div>
                            </div>
                            {#                                            <img src="{% static 'img/portfolio/eventex.png' %}" class="img-responsive" alt="">#}
                        </a>
                    </div>
                </div>

            </div>
            </div>
        </section>

        <!-- Subscript Grid Section -->
        <section class="success" id="subscription">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2>Inscrições</h2>
                        <a id="criar_atleta" href="#" class="portfolio-link" data-toggle="modal">
                            <div class="caption">
                                <div class="caption-content">
                                    <button type="submit" class="btn btn-primary">Novo atleta</button>
                                    {#                                    <i class="fa fa-search-plus fa-3x"></i>#}
                                </div>
                            </div>
                            {#                                            <img src="{% static 'img/portfolio/eventex.png' %}" class="img-responsive" alt="">#}
                        </a>
                    </div>
                </div>

            </div>
        </section>
        <!-- Footer -->
        <section id="subscription" style="padding-top: 150px;">
            <footer class="text-center">
                <div class="footer-above">
                    <div class="container">
                        <div class="row">
                            <div class="footer-col col-md-4">
                                <h3>Localização</h3>

                                <p>Av. Fialho de Almeida, 7800-395<br>
                                    2º andar, Edifício Hotel Melius<br>Beja Portugal</p>
                            </div>
                            <div class="footer-col col-md-4">
                                <h3>Redes sociais</h3>
                                <ul class="list-inline">
                                    <li>
                                        <a href="https://www.facebook.com/Kett-Clube-409334749265572/?fref=ts&__mref=message_bubble"
                                           class="btn-social btn-outline"><i
                                                class="fa fa-fw fa-facebook"></i></a>
                                    </li>
                                    <li>
                                        <a href="#" class="btn-social btn-outline"><i
                                                class="fa fa-fw fa-google-plus"></i></a>
                                    </li>
                                    <li>
                                        <a href="#" class="btn-social btn-outline"><i
                                                class="fa fa-fw fa-twitter"></i></a>
                                    </li>
                                </ul>
                            </div>
                            <div class="footer-col col-md-4">
                                <h3>Contatos</h3>

                                <p>Email: kettclub@gmail.com</p>

                                {#                        <p>Telefone:</p>#}

                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-below">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                Copyright &copy; Adriano Regis 2016
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <div>-</div>
        </section>
        </body>
    </section>
{% endblock content %}
</html>
{% block javascript %}

    <script src="{% static 'js/plugins/jquery.datatables.min.js' %}"></script>
    <script src="{% static 'js/plugins/datatables.bootstrap.min.js' %}"></script>



    <!-- custom -->
    {#    <script src="{% static 'js/main.js' %}"></script>#}
    <script type="text/javascript">

        $(document).ready(function () {
            console.log("ready atleta!");
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }


            $("#criar_atleta").click(function () {
                var csrftoken = getCookie('csrftoken');
                console.log("NOVO!");
                $.ajax({
                    url: "{% url 'external:new' %}",
                    type: 'GET',
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        console.log("index atleta!");
                        {#                      console.log(data);#}
                        $(".form_id").html(data);
                    }
                });
            });
        });
    </script>


{% endblock javascript %}

kettclub/core/templates/login_form.html
{% extends "base.html" %}
{% load static %}


{% block nav %}
{#    <div class="header-frame row">#}
{#        {% include 'nav.html' only %}#}
{#    </div>#}
{% endblock nav %}

{% block content %}
    <section id="subscription" style="padding-top: 200px;">
        <div class="container">
            <!--login modal-->
            {#            <div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">#}
            <div class="modal-dialog">
                <div class="modal-content col-sm-10">
                    <div class="modal-header">
{#                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>#}
                        <h1 class="text-center">Login</h1>
                    </div>
                    <div class="modal-body">
                        {% if form.errors %}
                            <div class="text-danger">Username ou Password incorretos.</div>
                        {% endif %}

                            {#                            <form class="form col-md-12 center-block">#}

                        <form method="POST" autocomplete="off" action="/login/" class="form col-md-12 center-block">
                            {% csrf_token %}
                            <div class="form-group row {% if form.username.errors %}has-error{% endif %}">
                                <label for="{{ form.username.label }}">{{ form.username.label }}</label>
                                {% if form.username.errors %}
                                    <span class="help-block">
                                    {% for error in form.username.errors %}{{ error }}{% endfor %}
                                  </span>
                                {% endif %}
                                {{ form.username }}
                                {#                                    <input type="text" class="form-control input-lg" placeholder="Email">#}
                            </div>
                            <div class="form-group row {% if form.password.errors %}has-error{% endif %}">
                                <label for="{{ form.password.label }}">{{ form.password.label }}</label>
                                {% if form.password.errors %}
                                    <span class="help-block">
                                    {% for error in form.username.errors %}{{ error }}{% endfor %}
                                  </span>
                                {% endif %}
                                {{ form.password }}
                                {#                                    <input type="password" class="form-control input-lg" placeholder="Password">#}
                            </div>

                            <div class="form-group">
                                <button class="btn btn-primary btn-lg btn-block">Entrar</button>
{#                                <input type="hidden" name="next" value="/dashboard/{{ user.pk }}" />#}
{#                                <span class="pull-right"><a href="#">Register</a></span><span><a href="#">Need#}
{#                                help?</a></span>#}
                            </div>
                            <div class="modal-footer">
                                <div class="col-md-12">
                                    <button type="reset" class="btn btn-primary" data-dismiss="modal"
                                            aria-hidden="true">
                                        Cancelar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        {#        </div>#}
    </section>
{% endblock content %}

kettclub/core/templates/nav.html
{% load static %}
<div class="container-fluid mimin-wrapper">
{#    <!-- Navebar top -->#}
{#    <nav class="navbar navbar-default header navbar-fixed-top">#}
{#        <div class="col-md-12 nav-wrapper">#}
{#            <div class="navbar-header" style="width:100%;">#}
{#                <div class="opener-left-menu is-open">#}
{#                    <span class="top"></span>#}
{#                    <span class="middle"></span>#}
{#                    <span class="bottom"></span>#}
{#                </div>#}
{#                <a href="/" class="navbar-brand">#}
{#                    <b class="fa-home fa"> KETTCLUB</b>#}
{#                </a>#}
{#                <ul class="nav navbar-nav navbar-right user-nav">#}
{#                    <li class="user-name">#}
{#                        {% if user.is_authenticated %}#}
{#                            <span>{{ request.user.username.title }}</span>#}
{#                        {% else %}#}
{#                            Utilizador#}
{#                        {% endif %}#}
{#                    </li>#}
{#                    <li class="dropdown avatar-dropdown">#}
{#                        <img src="{% static 'img/avatar.jpg' %}" class="img-circle avatar" alt="user name"#}
{#                             data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>#}
{#                        <ul class="dropdown-menu user-dropdown">#}
{#                            <li><a href="/config/settings/perfil/{{ request.user.pk }}"><span#}
{#                                    class="fa fa-user"></span>Profile</a></li>#}
{#                            <li role="separator" class="divider"></li>#}
{#                            <li class="more">#}
{#                                <ul>#}
{#                                    <li><a href=""><span class="fa fa-cogs"></span></a></li>#}
{#                                    <li><a href=""><span class="fa fa-lock"></span></a></li>#}
{#                                    <li><a href="{% url 'administration:logout' %}"><span#}
{#                                            class="fa fa-power-off "></span></a></li>#}
{#                                </ul>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </li>#}
{#                </ul>#}
{#            </div>#}
{#        </div>#}
{#    </nav>#}
{#    <!-- end: Navebar top -->#}
    <!-- start:Left Menu -->
    <div id="left-menu">
        <div class="sub-left-menu scroll" tabindex="5000" style="overflow: hidden; outline: none;">
            <ul class="nav nav-list">
                <li>
                    <div class="left-bg"></div>
                </li>
                <li class="time">
                    <h1 class="animated fadeInLeft">21:00</h1>

                    <p class="animated fadeInRight">Sat,October 1st 2029</p>
                </li>
                {% if not user.is_authenticated %}
                    <li class="active ripple">
                        <a href="{% url 'administration:dash' %}" class="nav-header"><span class="fa-cogs fa"></span>
                            Login sistema
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                    </li>
                {% else %}
                    <li class="active ripple">
                        <a href="{% url 'administration:dash' %}" class="nav-header"><span
                                class="fa-dashboard fa"></span>
                            Dashboard
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa-users fa"></span> Administração dados
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>

                        <ul class="nav nav-list tree">

                            <li><a href="{% url 'subscriptions:list' %}">Inscrição atletas</a></li>
                            <li><a href="{% url 'healthanamnese:list' %}">Saúde e Anamnese</a></li>
                            <li><a href="{% url 'reviewsphysicals:list' %}">Avaliação física</a></li>
                            <li><a href="{% url 'assiduousness:list' %}">Assiduidade atleta</a></li>
                            <li><a href="{% url 'monthlyplans:list' %}">Planos mensais</a></li>

                            {#                        <li><a href="#">Anamnese desportiva</a></li>#}
                            {#                        <li><a href="#">Avaliação física</a></li>#}
                        </ul>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa-edit fa"></span> Config. do sistema
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>

                        <ul class="nav nav-list tree">

                            <li><a href="{% url 'config:listGrupos' %}">Grupos</a></li>
                            <li><a href="{% url 'config:listUsers' %}">Utilizadores</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

<!-- start: Mobile -->
<div id="mimin-mobile" class="reverse">
    <div class="mimin-mobile-menu-list">
        <div class="col-md-12 sub-mimin-mobile-menu-list animated fadeInLeft">
            <ul class="nav nav-list">
                <li class="active ripple">
                    {% if not user.is_authenticated %}
                    <li class="active ripple">
                        <a href="{% url 'administration:dash' %}" class="nav-header"><span class="fa-cogs fa"></span>
                            Login sistema
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                    </li>
                {% else %}
                    <li class="active ripple">
                        <a href="{% url 'administration:dash' %}" class="nav-header"><span
                                class="fa-dashboard fa"></span>
                            Dashboard
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                    </li>
                {% endif %}
                </li>
                {% if user.is_authenticated %}
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa-users fa"></span> Administração dados
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>

                        <ul class="nav nav-list tree">

                            <li><a href="{% url 'subscriptions:list' %}">Inscrição atletas</a></li>
                            <li><a href="{% url 'healthanamnese:list' %}">Saúde e Anamnese</a></li>
                            <li><a href="{% url 'reviewsphysicals:list' %}">Avaliação física</a></li>
                            <li><a href="{% url 'assiduousness:list' %}">Assiduidade atleta</a></li>
                            <li><a href="{% url 'monthlyplans:list' %}">Planos mensais</a></li>

                            {#                        <li><a href="#">Anamnese desportiva</a></li>#}
                            {#                        <li><a href="#">Avaliação física</a></li>#}
                        </ul>
                    </li>
                    </li>
                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa-edit fa"></span> Config. do sistema
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>

                        <ul class="nav nav-list tree">

                            <li><a href="{% url 'config:listGrupos' %}">Grupos</a></li>
                            <li><a href="{% url 'config:listUsers' %}">Utilizadores</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
<button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
    <span class="fa fa-bars"></span>
</button>
<!-- end: Mobile -->

kettclub/core/templates/nav_old.html
{% load static %}
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Kettclub</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="{% url 'home' %}#page-top">Início</a>
                </li>
                <li class="page-scroll">
                    <a href="{% url 'assiduousness:new' %}" class="portfolio-link" data-toggle="modal">Presenças</a>
                </li>
                <li class="page-scroll">
                    <a href="{% url 'subscriptions:new' %}" class="portfolio-link" data-toggle="modal">Inscrições</a>
                </li>

                    <li class="page-scroll">
                    <a href="/administracao/" class="portfolio-link" data-toggle="modal">Administração</a>
                </li>
                    <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#" aria-expanded="false"><i class="glyphicon glyphicon-user"></i> Admin <span class="caret"></span></a>
                    <ul id="g-account-menu" class="dropdown-menu" role="menu">
                        <li><a href="#">My Profile</a></li>
                    </ul>
                </li>
                <li><a href="#"><i class="glyphicon glyphicon-lock"></i> Logout</a></li>
            </ul>
{#                <li class="page-scroll">#}
{#                    <a href="#contact">Contate-nos</a>#}
{#                </li>#}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

kettclub/core/templates/pagina_nao_autorizada.html
{#{% extends "base.html" %}#}
{% load static %}
{% load i18n %}


{% block content %}
    <!-- start: content -->
    <div class="col-md-12 text-center">
        <div class="alert-access-denied">
            <a href="#" onClick="history.go(-1)">
                <img src="{% static 'img/lock.png' %}">
            </a>
            <div>
                <h3><strong>Página não autorizada!</strong></h3>
                <p>Não está autorizado a aceder a esta página.<br/>Por favor contacte o administrador.
                    <br/><a href="#" onClick="history.go(-1)">Voltar à página anterior.</a></p>
            </div>
        </div>
    </div>
    <!-- end: content -->
{% endblock %}