kettclub/administration/urls.py
from django.conf.urls import url

from kettclub.administration.views import dash, Logout, Login

urlpatterns = [
    url(r'^login/', Login, name='login'),
    url(r'^logout/', Logout, name='logout'),
    url(r'^$', dash, name='dash'),
]

kettclub/monthlyplans/urls.py
from django.conf.urls import url
from kettclub.monthlyplans.views import new, editPlano, delDataModalPlano, \
    delConfirmePlano, listmonthlyplan, success, activeDataModalSubscription, activeConfirmeSubscription

urlpatterns = [
    url(r'^$', new, name='new'),
    url(r'^edit/(?P<pk>\d+)$', editPlano, name="edit"),
    url(r'^lista/', listmonthlyplan, name='list'),
    url(r'^deletar/', delDataModalPlano, name='delete'),
    url(r'^ativar/', activeDataModalSubscription, name='activate'),
    url(r'^confirmedeletar/', delConfirmePlano, name='delconfirme'),
    url(r'^confirmeativar/', activeConfirmeSubscription, name='activeconfirm'),
    url(r'^sucesso/', success, name='success'),
]

kettclub/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from kettclub.administration.views import Logout, Login
from kettclub.core.views import home, unauthorized
from kettclub.exercises.api import views as exercises_api_views
admin.site.site_header = 'Administração Kettclub'

urlpatterns = [
    url(r'^$', home.as_view(), name='home'),
    # url(r'^sucesso/', success.as_view(), name='success'),
    url(r'^naoautorizada/', unauthorized.as_view(), name='redirect'),

    url(r'^administracao/', include('kettclub.administration.urls',
                                namespace='administration')),
    url(r'^login/', Login, name='login'),

    url(r'^logout/$', Logout, name='logout'),
    # url(r'^novo/', include('kettclub.subscriptions.urls',
    #                             namespace='subscriptions')),
    url(r'^inscricao/', include('kettclub.subscriptions.urls',
                                namespace='subscriptions')),
    url(r'^inscricaoexterna/', include('kettclub.externalapplication.urls',
                                namespace='external')),
    url(r'^presenca/', include('kettclub.assiduousness.urls',
                               namespace='assiduousness')),
    url(r'^avaliacaofisica/', include('kettclub.reviewsphysicals.urls',
                                      namespace='reviewsphysicals')),
    url(r'^planosmensais/', include('kettclub.monthlyplans.urls',
                                      namespace='monthlyplans')),
    url(r'^saudeanamnese/', include('kettclub.healthanamnese.urls',
                                    namespace='healthanamnese')),
    url(r'^config/', include('kettclub.config.urls',
                                    namespace='config')),
    url(r'^exercise/', include('kettclub.exercises.urls', namespace="exercise")),
    url(r'^api/v2/exercise/search/$',
        exercises_api_views.search,
        name='exercise-search'),
    url(r'^admin/', admin.site.urls),
]

kettclub/monthlyplans/models.py
from django.core.urlresolvers import reverse
from django.db import models

BOOL_CHOICES = ((True, 'Sim'), (False, 'Não'))


class PlanoMensalidade(models.Model):
    nome = models.CharField('Nome do plano', max_length=50)
    valor = models.DecimalField('Valor €', max_digits=5, decimal_places=2)
    horario = models.CharField('Horário', max_length=20)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    ativo = models.BooleanField('Ativo', default=True, choices=BOOL_CHOICES)

    class Meta:
        verbose_name_plural = 'Planos e mensalidade'
        verbose_name = 'Plano e mensalidade'
        ordering = ('valor',)

    def get_absolute_url(self):
        return reverse('editatleta', kwargs={'pk': self.pk})

    def __str__(self):
        return self.nome + ' - ' + str(self.valor) + '€'

kettclub/monthlyplans/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from kettclub.monthlyplans.models import PlanoMensalidade

BOOL_CHOICES = ((True, 'Sim'), (False, 'Não'))


class MonthlyPlansForm(ModelForm):
    nome = forms.CharField(label='Nome', widget=forms.TextInput(
        attrs={'placeholder': 'Nome', 'class': 'form-control'}))
    valor = forms.DecimalField(label='Valor €', widget=forms.TextInput(
        attrs={'placeholder': 'Euros', 'class': 'form-control'}))
    horario = forms.CharField(label='Horário', widget=forms.TextInput(
        attrs={'placeholder': 'Horário ou período', 'class': 'form-control'}))
    ativo = forms.ChoiceField(BOOL_CHOICES,
                              label=('Ativo'),
                              widget=forms.Select(attrs={'placeholder': '--',
                                                         'class': 'form-control input-sm medio required_form'}))

    class Meta:
        model = PlanoMensalidade
        fields = ['nome', 'valor', 'horario', 'ativo']

# class EditSubscriptionForm(ModelForm):
#     error_messages = {
#         'err_code': (u"Já existe uma função com essa sigla."),
#         'required': (u'O campo é obrigatório.'),
#     }
#
#     ativo = forms.ChoiceField(BOOL_CHOICES,
#                               label=('Ativo'),
#                               widget=forms.Select(attrs={'placeholder': '--',
#                                                          'class': 'form-control input-sm medio required_form'})
#                               )
#     nome = forms.CharField(label='Nome', widget=forms.TextInput(
#         attrs={'placeholder': 'Nome', 'class': 'form-control'}))
#     sobrenome = forms.CharField(label='Sobrenome', widget=forms.TextInput(
#         attrs={'placeholder': 'Sobrenome', 'class': 'form-control'}))
#     emailatleta = forms.EmailField(label='Email', widget=forms.TextInput(
#         attrs={'placeholder': 'Email', 'class': 'form-control'}))
#     datainicio = forms.DateField(label='Data inicio',
#                                  widget=forms.DateInput(
#                                      attrs={'placeholder': 'dd/mm/yyyy', 'class': 'form-control date',
#                                             ' data-provide': 'datepicker',
#                                             'data-date-format': 'dd/mm/yyyy'}))
#     datanascimento = forms.DateField(label='Data de Nascimento',
#                                      widget=forms.DateInput(
#                                          attrs={'placeholder': 'dd/mm/yyyy', 'class': 'form-control date',
#                                                 ' data-provide': 'datepicker',
#                                                 'data-date-format': 'dd/mm/yyyy'}))
#     idade = forms.CharField(label='Idade', required=False, widget=forms.TextInput(
#         attrs={'placeholder': 'Idade', 'class': 'form-control'}))
#     nif = forms.CharField(label='NIF', widget=forms.TextInput(
#         attrs={'placeholder': 'Número de identificação fiscal', 'class': 'form-control'}))
#     cc = forms.CharField(label='CC', widget=forms.TextInput(
#         attrs={'placeholder': 'Cartão do Cidadão', 'class': 'form-control'}))
#
#     telefone = forms.CharField(label='Telefone', required=False, widget=forms.TextInput(
#         attrs={'placeholder': 'Contato', 'class': 'form-control'}))
#     telefone2 = forms.CharField(label='Telefone 2', required=False, widget=forms.TextInput(
#         attrs={'placeholder': 'Contato urgente', 'class': 'form-control'}))
#     # planomensalidade = forms.CharField(label='Plano', widget=forms.TextInput(
#     #     attrs={'placeholder': 'Plano mensalidade', 'class': 'form-control'}))
#
#     planomensalidade = forms.ModelChoiceField(PlanoMensalidade.objects.all(),
#                                               label=('Plano'),
#                                               widget=forms.Select(attrs={'placeholder': 'Plano mensalidade',
#                                                                          'class': 'form-control input-sm medio required_form'})
#                                               )
#
#     class Meta:
#         model = Subscription
#         # model = PlanoMensalidade
#         fields = ['ativo', 'nome', 'sobrenome', 'emailatleta', 'datainicio', 'datanascimento', 'idade', 'nif', 'cc',
#                   'telefone',
#                   'telefone2', 'planomensalidade']
#
#     # def __init__(self, emailatleta, *args, **kwargs):
#     #     super(EditSubscriptionForm, self).__init__(*args, **kwargs)
#     #     self.emailatleta = emailatleta
#
#     def clean_code(self):
#         emailatleta = self.cleaned_data["emailatleta"]
#         if self.emailatleta != emailatleta:
#             try:
#                 Subscription.objects.get(emailatleta=emailatleta)
#             except Subscription.DoesNotExist:
#                 return emailatleta
#             raise forms.ValidationError(self.error_messages['err_code'])
#         else:
#             return emailatleta


# class FichaSubscriptionForm(ModelForm):
#     nome = forms.CharField(label='Nome', widget=forms.TextInput(
#         attrs={'placeholder': 'Nome', 'class': 'form-control'}))
#     sobrenome = forms.CharField(label='Sobrenome', widget=forms.TextInput(
#         attrs={'placeholder': 'Sobrenome', 'class': 'form-control'}))
#     emailatleta = forms.EmailField(label='Email', widget=forms.TextInput(
#         attrs={'placeholder': 'Email', 'class': 'form-control'}))
#     datainicio = forms.DateField(label='Data inicio',
#                                  widget=forms.DateInput(
#                                      attrs={'placeholder': 'dd/mm/yyyy', 'class': 'form-control date',
#                                             ' data-provide': 'datepicker',
#                                             'data-date-format': 'dd/mm/yyyy'}))
#     datanascimento = forms.DateField(label='Data de Nascimento',
#                                      widget=forms.DateInput(
#                                          attrs={'placeholder': 'dd/mm/yyyy', 'class': 'form-control date',
#                                                 ' data-provide': 'datepicker',
#                                                 'data-date-format': 'dd/mm/yyyy'}))
#     idade = forms.CharField(label='Idade', required=False, widget=forms.TextInput(
#         attrs={'placeholder': 'Idade', 'class': 'form-control'}))
#     nif = forms.CharField(label='NIF', widget=forms.TextInput(
#         attrs={'placeholder': 'Número de identificação fiscal', 'class': 'form-control'}))
#     cc = forms.CharField(label='CC', widget=forms.TextInput(
#         attrs={'placeholder': 'Cartão do Cidadão', 'class': 'form-control'}))
#
#     telefone = forms.CharField(label='Telefone', required=False, widget=forms.TextInput(
#         attrs={'placeholder': 'Contato', 'class': 'form-control'}))
#     telefone2 = forms.CharField(label='Telefone 2', required=False, widget=forms.TextInput(
#         attrs={'placeholder': 'Contato urgente', 'class': 'form-control'}))
#     # planomensalidade = forms.CharField(label='Plano', widget=forms.TextInput(
#     #     attrs={'placeholder': 'Plano mensalidade', 'class': 'form-control'}))
#
#     planomensalidade = forms.ModelChoiceField(PlanoMensalidade.objects.all(),
#                                               label=('Plano'),
#                                               widget=forms.Select(attrs={'placeholder': 'Plano mensalidade',
#                                                                          'class': 'form-control input-sm medio required_form'})
#                                               )
#
#     def __init__(self, *args, **kwargs):
#         super(FichaSubscriptionForm, self).__init__(*args, **kwargs)
#         # self.fields['coordenacao'].widget.attrs['disabled'] = "disabled"

kettclub/monthlyplans/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.shortcuts import resolve_url as r
from django.views.decorators.cache import cache_page

from kettclub.monthlyplans.forms import MonthlyPlansForm


# @cache_page(60)
from kettclub.monthlyplans.models import PlanoMensalidade


@login_required
def listmonthlyplan(request, *args, **kwargs):
    list_plans = PlanoMensalidade.objects.all()

    try:
        tamLista = len(list_plans)
    except:
        context = {
            'list': list_plans,
            'tamLista': 0
        }

        return render(request, "monthlyplans/index.html", context)

    tamLista = len(list_plans)
    context = {
        'list': list_plans,
        'tamLista': tamLista
    }

    return render(request, "monthlyplans/index.html", context)


def new(request):
    if request.method == 'POST':
        return create(request)

    return empty_form(request)


def empty_form(request):
    return render(request, 'monthlyplans/add.html',
                  {'form': MonthlyPlansForm()})


@login_required
def create(request):
    form = MonthlyPlansForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'monthlyplans/add.html', {'form': form})

    form.save()
    return HttpResponseRedirect(r('monthlyplans:success'))


@login_required
def editPlano(request, pk):
    plano = get_object_or_404(PlanoMensalidade, pk=pk)
    form = MonthlyPlansForm(request.POST or None, instance=plano)
    if not form.is_valid():
        return render(request, 'monthlyplans/edit.html', {'form': form, 'plano': plano})
    else:
        form.save()
        return HttpResponseRedirect(r('monthlyplans:success'))


@login_required
def success(request):
    return render(request, 'monthlyplans/monthlyplans_success.html')


@login_required
def delDataModalPlano(request):
    id_list = []
    if request.is_ajax():
        select = request.POST.getlist('valores[]')

        for pk in select:
            id_list.append(int(pk))

    planos = PlanoMensalidade.objects.filter(pk__in=id_list, ativo=True)

    return render(request, 'monthlyplans/desativar_modal.html', {'planos': planos})


@login_required
def activeDataModalSubscription(request):
    print('XXXXXXXXXXXXXX: ', request.POST.getlist)
    id_list = []
    if request.is_ajax():
        select = request.POST.getlist('valores[]')

        for pk in select:
            id_list.append(int(pk))

    planos = PlanoMensalidade.objects.filter(pk__in=id_list, ativo=False)

    return render(request, 'monthlyplans/ativar_modal.html', {'planos': planos})


@login_required
def delConfirmePlano(request, *args, **kwargs):
    select = request.POST.getlist('valores_list[]')
    for valor in select:
        PlanoMensalidade.objects.filter(pk=valor).update(ativo=False)

    return HttpResponseRedirect(r('monthlyplans:list'))


@login_required
def activeConfirmeSubscription(request, *args, **kwargs):
    print('FFFFFFFFFFFFFFFFFFF')
    select = request.POST.getlist('valores_list[]')
    for valor in select:
        PlanoMensalidade.objects.filter(pk=valor).update(ativo=True)

    return HttpResponseRedirect(r('monthlyplans:list'))


# def deleteAtleta(request, pk):
#     plano = get_object_or_404(PlanoMensalidade, pk=pk)
#     if request.method=='POST':
#         # plano.delete()
#         plano.objects.filter(pk=pk).update(ativo=False)
#         return HttpResponseRedirect(r('monthlyplans:list'))
#     return render(request, 'monthlyplans/add.html', {'object':plano})

@login_required
def fichaPlano(request, *args, **kwargs):
    idPlano = kwargs['idPlano']

    editar = True
    saveNew = False

    planos = PlanoMensalidade.objects.get(id=idPlano)
    argCode = planos.pk

    if request.method == 'GET':
        url = reverse('/inscricao/ficha/' + idPlano)
        return HttpResponseRedirect(url)
    else:

        return HttpResponseRedirect(r('monthlyplans:list'))

kettclub/monthlyplans/templates/monthlyplans/ativar_modal.html
{% load i18n %}

<div class="col-md-12 modal-example">
    <div class="col-md-12">
        <div class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Grupos de Permissões</h4>
                    </div>
                    <div class="modal-body">
                        {% if planos %}
                            <p>{% trans "Deseja mesmo ativar o(s) plano(s):" %}</p>
                            <ul>
                                {% for plano in planos %}
                                    <li class="values_activeted"
                                        value="{{ plano.pk }}">{{ plano.nome }}</li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>{% trans "Não selecionou nenhuma plano!" %}</p>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Voltar
                                </button>
                            </div>
                        {% endif %}
                    </div>
                    {% if planos %}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar
                            </button>
                            <button id="btn_ativarSim" data-dismiss="modal" type="button" class="btn btn-primary">Sim
                            </button>
                        </div>
                    {% endif %}
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $('#btn_ativarSim').on("click", function () {
        console.log("ATIVA!");
            var ids = [];
            console.log(ids)
            $('.values_activeted').each(function () {
                ids.push($(this).val());
            });

            var target = "{%url 'monthlyplans:activeconfirm'%}"
            var csrftoken = getCookie('csrftoken');

            $('#ativarModal_atleta').modal('hide');

            $.ajax({
                type: "POST",
                url: target,
                data: {valores_list: ids},
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                },
                success: function (data) {
                    location.reload(true);//refresh na página
                    {#          		$('.form_id').html(data);#}
                    $('div').removeClass("modal-backdrop fade in");
                },
                error: function (rs, e) {

                }
            });
        });
    });


</script>

kettclub/monthlyplans/templates/monthlyplans/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{#{% block nav %}#}
{#    <div class="header-frame row">#}
{#        {% include 'nav.html' only %}#}
{#    </div>#}
{#{% endblock nav %}#}

{% block content %}
    <!-- start: Content -->
    <div id="content">
        <div class="panel box-shadow-none content-header">
            <div class="panel-body">
                <div class="col-md-12">
                    <h3 class="animated fadeInLeft">Planos Mensais</h3>
                    <p class="animated fadeInDown">
                        <a href="{% url 'administration:dash' %}">Dashboard</a> <span class="fa-angle-right fa"></span>
                        Planos Mensais
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-12 top-20">
            <div class="col-md-12 ">
                <div class="panel form_id">
                    <div class="panel-heading"><h3>Lista de planos</h3>
                        {% if tamLista != 0 %}
                            <div class="dropdown">
                                <input id="criar_plano" class="btn btn-primary" type="button"
                                       value="Novo"/>
                                <a href="#" data-toggle="dropdown" class="btn btn-default ">Mais<b
                                        class="caret"></b></a>

                                <ul class="dropdown-menu more" role="menu" aria-labelledby="dLabel">
                                    <li><a href="#" data-toggle="modal" data-target="#apagarModal_plano"
                                           class="men_apagar">{% trans 'Desativar' %}</a></li>
                                    <li><a href="#" data-toggle="modal" data-target="#ativarModal_plano"
                                           class="men_apagar">{% trans 'Ativar' %}</a></li>
                                    </ul>
                            </div>
                        {% endif %}
                        {% if tamLista == 0 %}
                            <div class="no_content">
                                <input id="criar_plano" class="btn btn-primary" type="button"
                                       value="Novo"/>
                                <img src="{% static 'img/empty_arrow_h.png' %}">
                                <p>Clique para criar um registo.</p>
                            </div>
                        {% else %}
                            </div>
                            <div class="panel-body">
                                <div class="responsive-table">
                                    <table id="datatables-example" class="table table-striped table-bordered"
                                           width="100%"
                                           cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th width="38px;"><input type="checkbox" class="checkAll"></th>
                                            <th>Nome</th>
                                            <th>Valor €</th>
                                            <th>Horário/Período</th>
                                            <th>Ativo</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for plano in list %}
                                            {% if plano.ativo == True %}
                                                <tr>
                                                    <td><input type="checkbox" value="{{ plano.pk }}"
                                                               class="checkable">
                                                    </td>
                                                    <td><a style="color: #337ab7" href="#"
                                                           class="edit_atleta navbar-link"
                                                           data-toggle="modal"
                                                           name="{{ plano.pk }}">{{ plano.nome }}</a>
                                                    </td>
                                                    <td>{{ plano.valor }}</td>
                                                    <td>{{ plano.horario }}</td>
                                                    <td>
                                                        <div style="color: #1B5E20"
                                                             class="glyphicon glyphicon-ok"></div>
                                                    </td>
                                                </tr>
                                            {% else %}
                                                <tr style="color: #c0c0c0">
                                                    <td><input type="checkbox" value="{{ plano.pk }}"
                                                               class="checkable">
                                                    </td>
                                                    <td><a style="color: #c0c0c0"
                                                           class="navbar-link"
                                                           data-toggle="modal"
                                                           name="{{ plano.pk }}">{{ plano.nome }}</a>
                                                    </td>
                                                    <td>{{ plano.valor }}</td>
                                                    <td>{{ plano.horario }}</td>
                                                    <td>
                                                        <div style="color: #cc1111"
                                                             class="glyphicon glyphicon-remove"></div>
                                                    </td>
                                                </tr>
                                            {% endif %}
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="apagarModal_plano" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true"></div>
    <div class="modal fade" id="ativarModal_plano" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true"></div>
    <!-- end: content -->

{% endblock content %}

{% block javascript %}

    <script src="{% static 'js/plugins/jquery.datatables.min.js' %}"></script>
    <script src="{% static 'js/plugins/datatables.bootstrap.min.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            console.log("ready plano!");
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            $('#datatables-example').DataTable({
                "oLanguage": {
                    "sUrl": "/static/dataTables/lang/pt-pt.txt"
                },
                "sScrollY": "710px",
                "bScrollCollapse": true,
                "bStateSave": true,
                "aoColumnDefs": [
                    {
                        'bSortable': false,
                        'aTargets': [0]
                    }
                ]

            });

            $('.checkAll').click(function () {
                console.log("checkAll!");
                $('input:checkbox.checkable').prop('checked', this.checked);
            });

            $("#criar_plano").click(function () {
                var csrftoken = getCookie('csrftoken');
                $.ajax({
                    url: "{% url 'monthlyplans:new'%}",
                    {#                                    url: "/inscricao/form",#}
                    type: 'GET',
                    data: {'value': ""},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        console.log("index plano!");
                        {#                      console.log(data);#}
                        $(".form_id").html(data);
                    }
                });
            });

            $(".edit_atleta").click(function () {
                var csrftoken = getCookie('csrftoken');
                var idPlano = $(this).attr("name");

                $.ajax({
                    url: '/planosmensais/edit/' + idPlano,
                    type: 'GET',
                    data: {},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        $(".form_id").html(data);
                    }
                });

            });

            $("#apagarModal_plano").on('show.bs.modal', function (event) {
                console.log("Apagar!");
                var vals = [];
                $('input:checked.checkable').each(function () {
                    var valor = $(this).val();
                    if (valor != undefined) {
                        vals.push(valor);
                    }
                });

                var target = "{%url 'monthlyplans:delete'%}"
                var csrftoken = getCookie('csrftoken');
                $.ajax({
                    type: "POST",
                    url: target,
                    data: {valores: vals},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        $('#apagarModal_plano').html(data);
                    },
                    error: function (rs, e) {

                    }
                });
            });

            $("#ativarModal_plano").on('show.bs.modal', function (event) {
                var vals = [];
                $('input:checked.checkable').each(function () {
                    var valor = $(this).val();
                    if (valor != undefined) {
                        vals.push(valor);
                    }
                });
                var target = "{%url 'monthlyplans:activate'%}"
                var csrftoken = getCookie('csrftoken');
                $.ajax({
                    type: "POST",
                    url: target,
                    data: {valores: vals},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        $('#ativarModal_plano').html(data);
                    },
                    error: function (rs, e) {

                    }
                });
            });

        });
    </script>
{% endblock javascript %}