kettclub/exercises/urls.py
from django.conf.urls import patterns, url, include


# sub patterns for muscles
from kettclub.exercises.views.exercises import ExerciseListView, view
from kettclub.exercises.views.muscle import MuscleListView, MuscleAdminListView, MuscleAddView, MuscleUpdateView, \
    MuscleDeleteView

patterns_muscle = [
    url(r'^overview/$',
        MuscleListView.as_view(),
        name='overview'),
    url(r'^admin-overview/$',
        MuscleAdminListView.as_view(),
        name='admin-list'),
    url(r'^add/$',
        MuscleAddView.as_view(),
        name='add'),
    url(r'^(?P<pk>\d+)/edit/$',
        MuscleUpdateView.as_view(),
        name='edit'),
    url(r'^(?P<pk>\d+)/delete/$',
        MuscleDeleteView.as_view(),
        name='delete'),
]

# sub patterns for exercises
patterns_exercise = [
    url(r'^overview/$',
        ExerciseListView.as_view(),
        name='overview'),
    url(r'^(?P<id>\d+)/view/$',
        view,
        name='view'),
    url(r'^(?P<id>\d+)/view/(?P<slug>[-\w]*)/?$',
        view,
        name='view'),
    # url(r'^add/$',
    #     login_required(ExerciseAddView.as_view()),
    #     name='add'),
    # url(r'^(?P<pk>\d+)/edit/$',
    #     ExerciseUpdateView.as_view(),
    #     name='edit'),
    # url(r'^(?P<pk>\d+)/correct$',
    #     ExerciseCorrectView.as_view(),
    #     name='correct'),
    # url(r'^(?P<pk>\d+)/delete/$',
    #     ExerciseDeleteView.as_view(),
    #     name='delete'),
    # url(r'^pending/$',
    #     PendingExerciseListView.as_view(),
    #     name='pending'),
    # url(r'^(?P<pk>\d+)/accept/$',
    #     accept,
    #     name='accept'),
    # url(r'^(?P<pk>\d+)/decline/$',
    #     decline,
    #     name='decline'),
]

urlpatterns = [
   url(r'^muscle/', include(patterns_muscle, namespace="muscle")),
   # url(r'^image/', include(patterns_images, namespace="image")),
   # url(r'^comment/', include(patterns_comment, namespace="comment")),
   # url(r'^category/', include(patterns_category, namespace="category")),
   # url(r'^equipment/', include(patterns_equipment, namespace="equipment")),
   url(r'^', include(patterns_exercise, namespace="exercise")),
]

kettclub/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from kettclub.administration.views import Logout, Login
from kettclub.core.views import home, unauthorized
from kettclub.exercises.api import views as exercises_api_views
admin.site.site_header = 'Administração Kettclub'

urlpatterns = [
    url(r'^$', home.as_view(), name='home'),
    # url(r'^sucesso/', success.as_view(), name='success'),
    url(r'^naoautorizada/', unauthorized.as_view(), name='redirect'),

    url(r'^administracao/', include('kettclub.administration.urls',
                                namespace='administration')),
    url(r'^login/', Login, name='login'),

    url(r'^logout/$', Logout, name='logout'),
    # url(r'^novo/', include('kettclub.subscriptions.urls',
    #                             namespace='subscriptions')),
    url(r'^inscricao/', include('kettclub.subscriptions.urls',
                                namespace='subscriptions')),
    url(r'^inscricaoexterna/', include('kettclub.externalapplication.urls',
                                namespace='external')),
    url(r'^presenca/', include('kettclub.assiduousness.urls',
                               namespace='assiduousness')),
    url(r'^avaliacaofisica/', include('kettclub.reviewsphysicals.urls',
                                      namespace='reviewsphysicals')),
    url(r'^planosmensais/', include('kettclub.monthlyplans.urls',
                                      namespace='monthlyplans')),
    url(r'^saudeanamnese/', include('kettclub.healthanamnese.urls',
                                    namespace='healthanamnese')),
    url(r'^config/', include('kettclub.config.urls',
                                    namespace='config')),
    url(r'^exercise/', include('kettclub.exercises.urls', namespace="exercise")),
    url(r'^api/v2/exercise/search/$',
        exercises_api_views.search,
        name='exercise-search'),
    url(r'^admin/', admin.site.urls),
]

kettclub/exercises/models.py
import uuid as uuid

import bleach as bleach

import six
from django.contrib.auth.models import User
from django.core import mail
from django.core.urlresolvers import reverse
from django.db import models
from django.template.loader import render_to_string
from django.utils import translation
from django.utils.text import slugify
from kettclub import settings


class Muscle(models.Model):
    '''
    Muscle an exercise works out
    '''

    name = models.CharField(max_length=50,
                            verbose_name=('Name'),
                            help_text=('In latin, e.g. "Pectoralis major"'))

    # Whether to use the front or the back image for background
    is_front = models.BooleanField(default=1)

    # Metaclass to set some other properties
    class Meta:
        ordering = ["name", ]

    def __str__(self):
        '''
        Return a more human-readable representation
        '''
        return self.name

    def get_owner_object(self):
        '''
        Muscle has no owner information
        '''
        return False


class Equipment(models.Model):
    '''
    Equipment used or needed by an exercise
    '''

    name = models.CharField(max_length=50,
                            verbose_name=('Name'))

    class Meta:
        '''
        Set default ordering
        '''
        ordering = ["name", ]

    def __str__(self):
        '''
        Return a more human-readable representation
        '''
        return self.name

    def get_owner_object(self):
        '''
        Equipment has no owner information
        '''
        return False


class ExerciseCategory(models.Model):
    '''
    Model for an exercise category
    '''
    name = models.CharField(max_length=100,
                            verbose_name=('Name'),)

    # Metaclass to set some other properties
    class Meta:
        verbose_name_plural = ("Exercise Categories")
        ordering = ["name", ]

    def __str__(self):
        '''
        Return a more human-readable representation
        '''
        return self.name

    def get_owner_object(self):
        '''
        Category has no owner information
        '''
        return False


class Exercise(models.Model):
    '''
    Model for an exercise
    '''
    license_author = models.CharField(max_length=200)

    category = models.ForeignKey(ExerciseCategory,
                                 verbose_name=('Category'))
    description = models.TextField(max_length=2000,
                                   verbose_name=('Description'))
    '''Description on how to perform the exercise'''

    name = models.CharField(max_length=200,
                            verbose_name=('Name'))

    muscles = models.ManyToManyField(Muscle,
                                     blank=True,
                                     verbose_name=('Primary muscles'))
    '''Main muscles trained by the exercise'''

    muscles_secondary = models.ManyToManyField(Muscle,
                                               verbose_name=('Secondary muscles'),
                                               related_name='secondary_muscles',
                                               blank=True)
    '''Secondary muscles trained by the exercise'''

    equipment = models.ManyToManyField(Equipment,
                                       verbose_name=('Equipment'),
                                       blank=True)
    '''Equipment needed by this exercise'''

    creation_date = models.DateField(('Date'),
                                     auto_now_add=True,
                                     null=True,
                                     blank=True)
    '''The submission date'''

    language = models.IntegerField(1)
    '''The exercise's language'''

    license = models.IntegerField(1)
    '''The exercise's language'''

    uuid = models.CharField(verbose_name='UUID',
                            max_length=36,
                            editable=False,
                            default=uuid.uuid4)
    '''
    Globally unique ID, to identify the exercise across installations
    '''

    status = models.IntegerField(1)
    '''The exercise's language'''

    #
    # Django methods
    #
    class Meta:
        ordering = ["name", ]

    def get_absolute_url(self):
        '''
        Returns the canonical URL to view an exercise
        '''
        return reverse('exercise:exercise:view', kwargs={'id': self.id, 'slug': slugify(self.name)})

    def save(self, *args, **kwargs):
        '''
        Reset all cached infos
        '''

        super(Exercise, self).save(*args, **kwargs)

    def __str__(self):
        '''
        Return a more human-readable representation
        '''
        return self.name

    #
    # Own methods
    #

    @property
    def main_image(self):
        '''
        Return the main image for the exercise or None if nothing is found
        '''
        return self.exerciseimage_set.filter(is_main=True).first()

    @property
    def description_clean(self):
        '''
        Return the exercise description with all markup removed
        '''
        return bleach.clean(self.description, strip=True)

    def get_owner_object(self):
        '''
        Exercise has no owner information
        '''
        return False

    def send_email(self, request):
        '''
        Sends an email after being successfully added to the database (for user
        submitted exercises only)
        '''
        try:
            user = User.objects.get(username=self.license_author)
        except User.DoesNotExist:
            return
        if self.license_author and user.email:
            translation.activate(user.userprofile.notification_language.short_name)
            url = request.build_absolute_uri(self.get_absolute_url())
            subject = ('Exercise was successfully added to the general database')
            context = {
                'exercise': self.name,
                'url': url
            }
            message = render_to_string('exercise/email_new.html', context)
            mail.send_mail(subject,
                           message,
                           settings.WGER_SETTINGS['EMAIL_FROM'],
                           [user.email],
                           fail_silently=True)

    def set_author(self, request):
        '''
        Set author and status
        This is only used when creating exercises (via web or API)
        '''
        if request.user.has_perm('exercises.add_exercise'):
            self.status = self.STATUS_ACCEPTED
            if not self.license_author:
                self.license_author = request.get_host().split(':')[0]
        else:
            if not self.license_author:
                self.license_author = request.user.username

            subject = ('New user submitted exercise')
            message = (u'The user {0} submitted a new exercise "{1}".').format(
                request.user.username, self.name)
            mail.mail_admins(six.text_type(subject),
                             six.text_type(message),
                             fail_silently=True)


def exercise_image_upload_dir(instance, filename):
    '''
    Returns the upload target for exercise images
    '''
    return "exercise-images/{0}/{1}".format(instance.exercise.id, filename)


class ExerciseImage(models.Model):
    '''
    Model for an exercise image
    '''

    exercise = models.ForeignKey(Exercise,
                                 verbose_name=('Exercise'))
    '''The exercise the image belongs to'''

    image = models.ImageField(verbose_name=('Image'),
                              help_text=('Only PNG and JPEG formats are supported'),
                              upload_to=exercise_image_upload_dir)
    '''Uploaded image'''

    is_main = models.BooleanField(verbose_name=('Main picture'),
                                  default=False,
                                  help_text=("Tick the box if you want to set this image as the "
                                              "main one for the exercise (will be shown e.g. in "
                                              "the search). The first image is automatically "
                                              "marked by the system."))
    '''A flag indicating whether the image is the exercise's main image'''

    class Meta:
        '''
        Set default ordering
        '''
        ordering = ['-is_main', 'id']

    def save(self, *args, **kwargs):
        '''
        Only one image can be marked as main picture at a time
        '''
        if self.is_main:
            ExerciseImage.objects.filter(exercise=self.exercise).update(is_main=False)
            self.is_main = True
        else:
            if ExerciseImage.objects.accepted().filter(exercise=self.exercise).count() == 0 \
               or not ExerciseImage.objects.accepted() \
                            .filter(exercise=self.exercise, is_main=True)\
                            .count():
                self.is_main = True

    def delete(self, *args, **kwargs):
        '''
        Reset all cached infos
        '''
        super(ExerciseImage, self).delete(*args, **kwargs)

        # Make sure there is always a main image
        if not ExerciseImage.objects.accepted() \
                .filter(exercise=self.exercise, is_main=True).count() \
           and ExerciseImage.objects.accepted() \
                .filter(exercise=self.exercise) \
                .filter(is_main=False) \
                .count():

                image = ExerciseImage.objects.accepted() \
                    .filter(exercise=self.exercise, is_main=False)[0]
                image.is_main = True
                image.save()

    def get_owner_object(self):
        '''
        Image has no owner information
        '''
        return False

    def set_author(self, request):
        '''
        Set author and status
        This is only used when creating images (via web or API)
        '''

kettclub/exercises/forms.py
from django import forms

from kettclub.exercises.models import ExerciseImage, ExerciseComment


class ExerciseImageForm(forms.ModelForm):
    class Meta:
        model = ExerciseImage
        fields = ('image',
                  'is_main',
                  'license',
                  'license_author')


class CommentForm(forms.ModelForm):
    class Meta:
        model = ExerciseComment
        exclude = ('exercise',)

kettclub/exercises/views/muscle.py
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from kettclub.exercises.models import Muscle


class MuscleListView(ListView):
    '''
        Overview of all muscles and their exercises
    '''
    model = Muscle
    queryset = Muscle.objects.all().order_by('-is_front', 'name'),
    context_object_name = 'muscle_list'
    template_name = 'muscle/overview.html'

    def get_context_data(self, **kwargs):
        '''
        Send some additional data to the template
        '''
        context = super(MuscleListView, self).get_context_data(**kwargs)
        context['show_shariff'] = True
        return context


class MuscleAdminListView(MuscleListView):
    '''
    Overview of all muscles, for administration purposes
    '''
    permission_required = 'exercises.change_muscle'
    login_required = True
    queryset = Muscle.objects.order_by('name')
    template_name = 'muscle/admin-overview.html'


class MuscleAddView(CreateView):
    '''
    Generic view to add a new muscle
    '''

    model = Muscle
    fields = '__all__'
    success_url = reverse_lazy('exercise:muscle:admin-list')
    title = ugettext_lazy('Add muscle')
    form_action = reverse_lazy('exercise:muscle:add')
    # permission_required = 'exercises.add_muscle'


class MuscleUpdateView(UpdateView):
    model = Muscle
    success_url = reverse_lazy('muscle_list')
    fields = ['name']


class MuscleDeleteView(DeleteView):
    model = Muscle
    success_url = reverse_lazy('muscle_list')

kettclub/exercises/templates/equipment/list.html
{% extends "base.html" %}
{% load i18n staticfiles wger_extras %}

{% block title %}{% trans "Equipment list" %}{% endblock %}


{% block content %}
<ul class="list-group">
    {% for equipment in equipment_list %}
    <li class="list-group-item ">
        <div class="btn-group pull-right">
            <button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
                <span class="glyphicon glyphicon-cog"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li>
                    <a href="{% url 'exercise:equipment:edit' equipment.id %}" class="wger-modal-dialog">{% trans 'Edit' %}</a>
                </li>
                <li>
                    <a href="{% url 'exercise:equipment:delete' equipment.id %}" class="wger-modal-dialog">{% trans 'Delete' %}</a>
                </li>
            </ul>
        </div>
        {{equipment.name}}
    </li>
    {% empty %}
        <li class="list-group-item">
            {% trans "Nothing found" %}
        </li>
    {% endfor %}
</ul>
{% pagination paginator page_obj %}
{% endblock %}




{% block sidebar %}
{% if perms.exercises.add_equipment %}
<p>
    <a href="{% url 'exercise:equipment:add' %}" class="btn btn-success btn-sm wger-modal-dialog">
        {% trans "Add new equipment" %}
    </a>
</p>
{% endif %}
{% endblock %}

kettclub/exercises/templates/equipment/overview.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load wger_extras %}
{% load cache %}
{% load thumbnail %}

<!--
        Title
-->
{% block title %}{% trans "Equipment overview" %}{% endblock %}


{% block header %}
 <script>
$(function() {
    // Init the autocompleter
    $("#exercise-search").catcomplete({
            source: "{% url 'exercise-search' %}",
            minLength: 2,
            select: function(event, ui) {

                // Redirect to exercise after clicking on a result
                // Path is hard coded here, because we can't use the url-tag
                window.location.href = '/exercise/' + ui.item.id + '/view/'
            }
    });
});
</script>
{% endblock %}


<!--
        Main Content
-->
{% block content %}
{% cache cache_timeout equipment-overview language.id %}
<div class="panel-group" id="accordion">
    {% for equipment in equipment_list %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse-{{equipment.pk}}">
                    {% trans equipment.name %}
                </a>
            </h4>
        </div>
        <div id="collapse-{{equipment.pk}}" class="panel-collapse collapse">
            <div class="panel-body">
                <div class="list-group">
                    {% for exercise in equipment.exercise_set.all %}
                    {% if exercise.language in exercise_languages %}
                    <a href="{{ exercise.get_absolute_url }}" class="list-group-item">
                        <div class="media">
                            <div style="width:60px;height:60px;" class="media-left">

                            {% if exercise.main_image %}
                                <img alt="{{ exercise.name }}"
                                 class="media-object "
                                 style="max-width:100%; max-height:100%;"
                                 src="{{ exercise.main_image.image|thumbnail_url:'thumbnail' }}">
                            {% else %}
                            <img alt="{% trans 'Placeholder image for exercise' %}"
                                 class="media-object "
                                 style="max-width:100%; max-height:100%; opacity: 0.4;"
                                 src="{% static 'images/icons/image-placeholder.svg' %}">
                            {% endif %}
                            </div>
                            <div class="media-body" style="position: absolute; top: 10px; left: 100px;">
                                <h4 class="media-heading">{{ exercise.name }}</h4>
                                <span class="text-muted">
                                    {% trans exercise.category.name %}
                                    <!--
                                    {% trans "Main muscles" %}: {{ exercise.muscles.all|join:", " }}
                                    <br>
                                    {% trans "Secondary muscles" %}: {{ exercise.muscles_secondary.all|join:", " }}
                                    -->
                                </span>
                             </div>
                        </div>
                    </a>
                    {% endif %}
                    {% empty %}
                        {% trans "No exercises for this equipment. Add or edit an exercise and set the equipment." %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endcache %}
{% endblock %}


<!--
        Side bar
-->
{% block sidebar %}
<p>
    {% if user.is_authenticated and not user.userprofile.is_temporary %}
    <a href="{% url 'exercise:exercise:add' %}" class="btn btn-success btn-sm">
        {% trans "Add new exercise" %}
    </a>
    {% else %}
    <a href="#" class="btn btn-success btn-sm disabled">
        {% trans "Add new exercise" %}<br>
        <small>
        {% trans "Only registered users can do this" %}
        </small>
    </a>
    {% endif %}
</p>



<h4>{% trans "Search" %}</h4>
<form action="{% url 'exercise-search' %}"
      method="get"
      id="exercise_search_form">
    {% csrf_token %}
    <input name="term"
           type="search"
           id="exercise-search"
           class="ajax-form-element form-control"
           placeholder="{% trans 'exercise name' %}"
           style="width:100%;">
</form>
{% endblock %}