kettclub/administration/urls.py
from django.conf.urls import url

from kettclub.administration.views import dash, Logout, Login

urlpatterns = [
    url(r'^login/', Login, name='login'),
    url(r'^logout/', Logout, name='logout'),
    url(r'^$', dash, name='dash'),
]

kettclub/reviewsphysicals/urls.py
from django.conf.urls import url
from kettclub.reviewsphysicals.views import new, editAvaliacao, listavaliacao, delDataModalAvaliacao, \
    delConfirmeAvaliacao, success

urlpatterns = [
    url(r'^$', new, name='new'),
    url(r'^edit/(?P<pk>\d+)$', editAvaliacao, name="editavaliacao"),
    url(r'^lista/', listavaliacao, name='list'),
    url(r'^deletar/', delDataModalAvaliacao, name='deletaravaliacao'),
    url(r'^confirmedeletar/', delConfirmeAvaliacao, name='delconfirme'),
    url(r'^sucesso/', success, name='success'),

]

kettclub/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from kettclub.administration.views import Logout, Login
from kettclub.core.views import home, unauthorized
from kettclub.exercises.api import views as exercises_api_views
admin.site.site_header = 'Administração Kettclub'

urlpatterns = [
    url(r'^$', home.as_view(), name='home'),
    # url(r'^sucesso/', success.as_view(), name='success'),
    url(r'^naoautorizada/', unauthorized.as_view(), name='redirect'),

    url(r'^administracao/', include('kettclub.administration.urls',
                                namespace='administration')),
    url(r'^login/', Login, name='login'),

    url(r'^logout/$', Logout, name='logout'),
    # url(r'^novo/', include('kettclub.subscriptions.urls',
    #                             namespace='subscriptions')),
    url(r'^inscricao/', include('kettclub.subscriptions.urls',
                                namespace='subscriptions')),
    url(r'^inscricaoexterna/', include('kettclub.externalapplication.urls',
                                namespace='external')),
    url(r'^presenca/', include('kettclub.assiduousness.urls',
                               namespace='assiduousness')),
    url(r'^avaliacaofisica/', include('kettclub.reviewsphysicals.urls',
                                      namespace='reviewsphysicals')),
    url(r'^planosmensais/', include('kettclub.monthlyplans.urls',
                                      namespace='monthlyplans')),
    url(r'^saudeanamnese/', include('kettclub.healthanamnese.urls',
                                    namespace='healthanamnese')),
    url(r'^config/', include('kettclub.config.urls',
                                    namespace='config')),
    url(r'^exercise/', include('kettclub.exercises.urls', namespace="exercise")),
    url(r'^api/v2/exercise/search/$',
        exercises_api_views.search,
        name='exercise-search'),
    url(r'^admin/', admin.site.urls),
]

kettclub/reviewsphysicals/models.py
from django.core.urlresolvers import reverse
from django.db import models
from kettclub.subscriptions.models import Subscription

BOOL_CHOICES = ((True, 'Sim'), (False, 'Não'))


class Avaliacao(models.Model):
    atleta = models.ForeignKey(Subscription, verbose_name='Nº do atleta')
    dataavaliacao = models.DateField('Data da avaliação')
    peso = models.DecimalField('Peso Kg', max_digits=4, decimal_places=2)
    metbasal = models.CharField('Met. basal Kcal', max_length=5)
    idadebiologica = models.IntegerField('Idade biológica anos')
    agua = models.DecimalField('Água %', max_digits=5, decimal_places=2)
    gorduraviceral = models.CharField('Gordura visceral nível', max_length=5)
    massaossea = models.DecimalField('Massa ossea kg', max_digits=4, decimal_places=2)
    massamuscular = models.DecimalField('Massa muscular total kg', max_digits=4, decimal_places=2)
    massagorda = models.DecimalField('Massa gorda total %', max_digits=4, decimal_places=2)
    pescoco = models.DecimalField('Pescoço cm', max_digits=4, decimal_places=2)
    ombros = models.DecimalField('Ombros cm', max_digits=4, decimal_places=2)
    peitos = models.DecimalField('Peitos cm', max_digits=4, decimal_places=2)
    cintura = models.DecimalField('Cintura cm', max_digits=4, decimal_places=2)
    abdominal = models.DecimalField('Abdominal cm', max_digits=4, decimal_places=2)
    quadril = models.DecimalField('Quadril cm', max_digits=4, decimal_places=2)
    coxaproximal = models.DecimalField('Coxa proximal cm', max_digits=4, decimal_places=2)
    coxamedial = models.DecimalField('Coxa medial cm', max_digits=4, decimal_places=2)
    created_at = models.DateTimeField('Avaliado em', auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Avaliações'
        verbose_name = 'Avaliação'
        ordering = ('atleta__nome',)

    def get_absolute_url(self):
        return reverse('editatleta', kwargs={'pk': self.pk})

    def __str__(self):
        return self.atleta.nome + ' ' + self.atleta.sobrenome

kettclub/reviewsphysicals/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from kettclub.reviewsphysicals.models import Avaliacao
from kettclub.subscriptions.models import Subscription


class EvaluationForm(ModelForm):
    atleta = forms.ModelChoiceField(Subscription.objects.all().order_by('pk'),
                                    label=('Nome'),
                                    widget=forms.Select(attrs={'placeholder': 'Nome do atleta',
                                                               'class': 'form-control input-sm medio required_form'})
                                    )
    dataavaliacao = forms.DateField(label='Data avaliação',
                                    widget=forms.DateInput(
                                        attrs={'placeholder': 'dia/mês/ano', 'class': 'form-control date',
                                               ' data-provide': 'datepicker',
                                               'data-date-format': 'dd/mm/yyyy'}))

    peso = forms.DecimalField(label='Peso Kg', widget=forms.TextInput(
        attrs={'placeholder': 'Kg', 'class': 'form-control'}))

    metbasal = forms.DecimalField(label='Met. basal Kcal', widget=forms.TextInput(
        attrs={'placeholder': 'Kcal', 'class': 'form-control'}))

    idadebiologica = forms.IntegerField(label='Idade biológica anos', widget=forms.TextInput(
        attrs={'placeholder': 'Anos', 'class': 'form-control'}))

    agua = forms.DecimalField(label='Água %', widget=forms.TextInput(
        attrs={'placeholder': '%', 'class': 'form-control'}))

    gorduraviceral = forms.CharField(label='Gordura visceral nível', widget=forms.TextInput(
        attrs={'placeholder': 'Nível', 'class': 'form-control'}))

    massaossea = forms.DecimalField(label='Massa ossea kg', widget=forms.TextInput(
        attrs={'placeholder': 'Kg', 'class': 'form-control'}))

    massamuscular = forms.DecimalField(label='Massa muscular total kg', widget=forms.TextInput(
        attrs={'placeholder': 'Kg', 'class': 'form-control'}))

    massagorda = forms.DecimalField(label='Massa gorda total %', widget=forms.TextInput(
        attrs={'placeholder': '%', 'class': 'form-control'}))

    pescoco = forms.DecimalField(label='Pescoço cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    ombros = forms.DecimalField(label='Ombros cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    peitos = forms.DecimalField(label='Peitos cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    cintura = forms.DecimalField(label='Cintura cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    abdominal = forms.DecimalField(label='Abdominal cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    quadril = forms.DecimalField(label='Quadril cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    coxaproximal = forms.DecimalField(label='Coxa proximal cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    coxamedial = forms.DecimalField(label='Coxa medial cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    class Meta:
        model = Avaliacao
        exclude = ['created_at']


class EditEvaluationForm(ModelForm):
    dataavaliacao = forms.DateField(label='Data avaliação',
                                    widget=forms.DateInput(
                                        attrs={'placeholder': 'dia/mês/ano', 'class': 'form-control date',
                                               ' data-provide': 'datepicker',
                                               'data-date-format': 'dd/mm/yyyy'}))

    peso = forms.DecimalField(label='Peso Kg', widget=forms.TextInput(
        attrs={'placeholder': 'Kg', 'class': 'form-control'}))

    metbasal = forms.DecimalField(label='Met. basal Kcal', widget=forms.TextInput(
        attrs={'placeholder': 'Kcal', 'class': 'form-control'}))

    idadebiologica = forms.IntegerField(label='Idade biológica anos', widget=forms.TextInput(
        attrs={'placeholder': 'Anos', 'class': 'form-control'}))

    agua = forms.DecimalField(label='Água %', widget=forms.TextInput(
        attrs={'placeholder': '%', 'class': 'form-control'}))

    gorduraviceral = forms.CharField(label='Gordura visceral nível', widget=forms.TextInput(
        attrs={'placeholder': 'Nível', 'class': 'form-control'}))

    massaossea = forms.DecimalField(label='Massa ossea kg', widget=forms.TextInput(
        attrs={'placeholder': 'Kg', 'class': 'form-control'}))

    massamuscular = forms.DecimalField(label='Massa muscular total kg', widget=forms.TextInput(
        attrs={'placeholder': 'Kg', 'class': 'form-control'}))

    massagorda = forms.DecimalField(label='Massa gorda total %', widget=forms.TextInput(
        attrs={'placeholder': '%', 'class': 'form-control'}))

    pescoco = forms.DecimalField(label='Pescoço cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    ombros = forms.DecimalField(label='Ombros cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    peitos = forms.DecimalField(label='Peitos cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    cintura = forms.DecimalField(label='Cintura cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    abdominal = forms.DecimalField(label='Abdominal cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    quadril = forms.DecimalField(label='Quadril cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    coxaproximal = forms.DecimalField(label='Coxa proximal cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    coxamedial = forms.DecimalField(label='Coxa medial cm', widget=forms.TextInput(
        attrs={'placeholder': 'cm', 'class': 'form-control'}))

    class Meta:
        model = Avaliacao
        exclude = ['atleta', 'created_at']

kettclub/reviewsphysicals/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.shortcuts import resolve_url as r
from kettclub.reviewsphysicals.forms import EvaluationForm, EditEvaluationForm
from kettclub.reviewsphysicals.models import Avaliacao
from kettclub.subscriptions.models import Subscription


@login_required
def listavaliacao(request, *args, **kwargs):
    list_ = Subscription.objects.all()

    if list_:
        data = Avaliacao.objects.filter()
        if not data:
            context = {
                'list': data,
                'tamLista': 0,
            }

            return render(request, "reviewsphysicals/index.html", context)
        else:
            context = {
                'list': data,
                'tamLista': 1,
            }

            return render(request, "reviewsphysicals/index.html", context)
    else:
        context = {
            'list_': 0
        }

        return render(request, "reviewsphysicals/index.html", context)


def new(request):
    if request.method == 'POST':
        return create(request)

    return empty_form(request)


def empty_form(request):
    return render(request, 'reviewsphysicals/add.html',
                  {'form': EvaluationForm()})


def empty_prototipo_form(request):
    return render(request, 'reviewsphysicals/evaluation_form.html',
                  {'form': EvaluationForm()})


@login_required
def create(request):
    form = EvaluationForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'reviewsphysicals/add.html', {'form': form})
    else:
        form.save()
        return HttpResponseRedirect(r('reviewsphysicals:success'))


@login_required
def editAvaliacao(request, pk):
    avaliacao = get_object_or_404(Avaliacao, pk=pk)
    form = EditEvaluationForm(request.POST or None, instance=avaliacao)
    if not form.is_valid():
        return render(request, 'reviewsphysicals/edit.html', {'form': form, 'avaliacao': avaliacao})
    else:
        form.save()
        return HttpResponseRedirect(r('reviewsphysicals:success'))


@login_required
def success(request):
    return render(request, 'reviewsphysicals/avaliation_success.html')


# def editAvaliacao(request, pk):
# avaliacao = get_object_or_404(Avaliacao, pk=pk)
# form = EditEvaluationForm(request.POST or None, instance=avaliacao)
# if not form.is_valid():
#     return render(request, 'reviewsphysicals/edit.html', {'form': form, 'avaliacao': avaliacao})
# else:
#     form.save()
#     return HttpResponseRedirect(r('reviewsphysicals:list'))


@login_required
def delDataModalAvaliacao(request):
    id_list = []
    if request.is_ajax():
        select = request.POST.getlist('valores[]')

        for pk in select:
            id_list.append(int(pk))

    avaliacoes = Avaliacao.objects.filter(pk__in=id_list, ativo=True)

    return render(request, 'reviewsphysicals/removeModal.html', {'avaliacoes': avaliacoes})


@login_required
def delConfirmeAvaliacao(request, *args, **kwargs):
    select = request.POST.getlist('valores_list[]')
    for valor in select:
        Avaliacao.objects.filter(pk=valor).update(ativo=False)

    return HttpResponseRedirect(r('reviewsphysicals:list'))


# def deleteAvaliacao(request, pk):
#     avaliacao = get_object_or_404(Avaliacao, pk=pk)
#     if request.method=='POST':
#         # avaliacao.delete()
#         avaliacao.objects.filter(pk=pk).update(ativo=False)
#         return HttpResponseRedirect(r('reviewsphysicals:list'))
#     return render(request, 'reviewsphysicals/add.html', {'object':avaliacao})


def fichaAvaliacao(request, *args, **kwargs):
    idAvaliacao = kwargs['idAvaliacao']

    editar = True
    saveNew = False

    avaliacoes = Avaliacao.objects.get(id=idAvaliacao)
    argCode = avaliacoes.pk

    if request.method == 'GET':
        url = reverse('/avaliacao/ficha/' + idAvaliacao)
        return HttpResponseRedirect(url)
    else:

        return HttpResponseRedirect(r('reviewsphysicals:list'))

kettclub/reviewsphysicals/templates/reviewsphysicals/avaliation_success.html
<form method="get" action="{% url 'reviewsphysicals:list' %}" class="form-horizontal">
    {% csrf_token %}
    <div class="col-md-8">
        <div class="panel form-element-padding">
            <div class="panel-heading">
                <h4>Ação</h4>
            </div>
            <div class="panel-body" style="padding-bottom:30px;">
                <div class="form-group">
                    <div class="col-sm-5">

                        <input type="submit" id="save" class="btn btn-primary" name="Save" value="Ok"
                               style="float:left;"/>
                    </div>
                </div>
                <div class="alert alert-success">
                    Ação realizada com sucesso!
                </div>
            </div>
        </div>
    </div>

</form>

kettclub/reviewsphysicals/templates/reviewsphysicals/evaluation_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Header -->
<section id="subscription" style="padding-top: 200px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                   <form method="post" action="{% url 'subscriptions:new' %}">
                    {% csrf_token %}
                       <iframe src="https://docs.google.com/forms/d/17KZqNVqaw67HwxceXG0an2oAWS7n1lsjIIU1RkJuijQ/viewform?embedded=true"
                                    width="100%" height="1532" frameborder="0" marginheight="0" marginwidth="0">A carregar...</iframe>
{#                    {{ form.as_p }}#}
                    <div class="text-center">
                        <button type="submit" class="btn btn-success" data-dismiss="modal">
                            <i class="fa fa-check-circle"></i> Novo
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

kettclub/reviewsphysicals/templates/reviewsphysicals/index.html
{% extends "base.html" %}
{% load static %}

{#{% block nav %}#}
{#    <div class="header-frame row">#}
{#        {% include 'nav.html' only %}#}
{#    </div>#}
{#{% endblock nav %}#}

{% block content %}
    <!-- start: Content -->
    <div id="content">
        <div class="panel box-shadow-none content-header">
            <div class="panel-body">
                <div class="col-md-12">
                    <h3 class="animated fadeInLeft">Avaliações físicas</h3>
                    <p class="animated fadeInDown">
                        <a href="{% url 'administration:dash' %}" >Dashboard</a> <span class="fa-angle-right fa"></span> Avaliação física
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-12 top-20">
            <div class="col-md-12 ">
                <div class="panel form_id">
                    <div class="panel-heading"><h3>Lista de avaliações</h3>
                    {% if list_ != 0 %}
                        {% if tamLista != 0 %}
                            <div class="dropdown">
                                <input id="criar_avaliacao" class="btn btn-primary" type="button"
                                       value="Novo"/>
{#                                <a href="#" data-toggle="dropdown" class="btn btn-default ">Mais<b#}
{#                                        class="caret"></b></a>#}
{##}
{#                                <ul class="dropdown-menu more" role="menu" aria-labelledby="dLabel">#}
{#                                    <li><a href="#" data-toggle="modal" data-target="#apagarModal_avaliacao"#}
{#                                           class="men_apagar">Desativar</a></li>#}
{#                                </ul>#}
                            </div>
                        {% endif %}
                        {% if tamLista == 0 %}
                            <div class="no_content">
                            <input id="criar_avaliacao" class="btn btn-primary" type="button"
                                       value="Novo"/>
                                <img src="{% static 'img/empty_arrow_h.png' %}">
                                <p>Clique para criar um registo.</p>
                            </div>
                        {% else %}
                            </div>
                            <div class="panel-body">
                                <div class="responsive-table">
                                    <table id="datatables-example" class="table table-striped table-bordered"
                                           width="100%"
                                           cellspacing="0">
                                        <thead>
                                        <tr>
{#                                            <th width="38px;"><input type="checkbox" class="checkAll"></th>#}
                                            <th>Nome</th>
                                            <th>Data da avaliação</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for avaliacao in list %}
                                                <tr>
{#                                                    <td><input type="checkbox" value="{{ avaliacao.pk }}"#}
{#                                                               class="checkable">#}
{#                                                    </td>#}
                                                    <td><a style="color: #337ab7" href="#"
                                                           class="edit_avaliacao navbar-link"
                                                           data-toggle="modal"
                                                           name="{{ avaliacao.pk }}">{{ avaliacao.atleta.nome }} {{ avaliacao.atleta.sobrenome }}</a>
                                                    </td>
                                                    <td>{{ avaliacao.dataavaliacao }}</td>
                                                </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        {% endif %}
                {% else %}
                <div class="no_content">
                            <input id="criar_avaliacao" class="btn btn-primary" type="button"
                                       value="Novo" disabled/>
                                <img src="{% static 'img/empty_arrow_h.png' %}">
                                <p>Habilitado após ser adicionado um atleta.</p>
                            </div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="apagarModal_avaliacao" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
    <!-- end: content -->

    <!-- start: Javascript -->
    {#    <script src="{% static 'js/jquery.min.js' %}"></script>#}
    {#    <script src="{% static 'js/jquery.ui.min.js' %}"></script>#}
    {#    <script src="{% static 'js/bootstrap.min.js' %}"></script>#}

    <!-- plugins -->
    {#    <script src="{% static 'js/plugins/moment.min.js' %}"></script>#}

    <!-- end: Javascript -->
{% endblock content %}

{% block javascript %}

    <script src="{% static 'js/plugins/jquery.datatables.min.js' %}"></script>
    <script src="{% static 'js/plugins/datatables.bootstrap.min.js' %}"></script>
    {#    <script src="{% static 'js/plugins/jquery.nicescroll.js' %}"></script>#}

    <!-- custom -->
    {#    <script src="{% static 'js/main.js' %}"></script>#}
    <script type="text/javascript">

        $(document).ready(function () {
            console.log("ready avaliacao!");
            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            $('#datatables-example').DataTable({
                "oLanguage": {
                    "sUrl": "/static/dataTables/lang/pt-pt.txt"
                },
                "sScrollY": "710px",
                "bScrollCollapse": true,
                "bStateSave": true,
                "aoColumnDefs": [
                    {
                        'bSortable': false,
                        'aTargets': [0]
                    }
                ]

            });

            $('.checkAll').click(function () {
                console.log("checkAll!");
                $('input:checkbox.checkable').prop('checked', this.checked);
            });

            $("#criar_avaliacao").click(function () {
                var csrftoken = getCookie('csrftoken');
                $.ajax({
                    url: "{% url 'reviewsphysicals:new' %}",
                    {#                                    url: "/avaliacaofisica/form",#}
                    type: 'GET',
                    data: {'value': ""},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        console.log("index avaliacao!");
                        {#                      console.log(data);#}
                        $(".form_id").html(data);
                    }
                });
            });

            $(".edit_avaliacao").click(function () {
                var csrftoken = getCookie('csrftoken');
                var idAvaliacao = $(this).attr("name");

                $.ajax({
                    url: '/avaliacaofisica/edit/' + idAvaliacao,
                    type: 'GET',
                    data: {},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        $(".form_id").html(data);
                    }
                });

            });

            $("#apagarModal_avaliacao").on('show.bs.modal', function (event) {
                console.log("Apagar!");
                var vals = [];
                $('input:checked.checkable').each(function () {
                    var valor = $(this).val();
                    if (valor != undefined) {
                        vals.push(valor);
                    }
                });
{#                var target = "{%url 'delDataModalAtleta'%}"#}
                var target = "/avaliacaofisica/deletar/"
                var csrftoken = getCookie('csrftoken');
                $.ajax({
                    type: "POST",
                    url: target,
                    data: {valores: vals},
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    },
                    success: function (data) {
                        $('#apagarModal_avaliacao').html(data);
                    },
                    error: function (rs, e) {

                    }
                });
            });

        });
    </script>
{% endblock javascript %}

kettclub/reviewsphysicals/templates/reviewsphysicals/removeModal.html
{% load i18n %}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-title">
            <span><b>{% trans "Apagar Atleta(s)" %}</b></span>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </span>
        </div>
        <div class="modal-body">
            {% if atletas %}
                <p>{% trans "Deseja mesmo apagar o(s) atleta(s):" %}</p>
                <ul>
                    {% for atleta in atletas %}
                        <li class="values_delete" value="{{ atleta.pk }}">{{ atleta.nome }} {{ atleta.sobrenome }}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>{% trans "Não selecionou nenhuma atleta!" %}</p>
                <div class="modal-footer">
                    <input id="" data-dismiss="modal" type="button" class="btn btn-primary" value="{% trans 'Voltar' %}"
                           style="float:left;">
                </div>
            {% endif %}
        </div>
        {% if atletas %}
            <div class="modal-footer">
                <input id="btn_apagarSim" data-dismiss="modal" type="button" class="btn btn-primary"
                       value="{% trans 'Sim' %}" style="float:left;">
                <div class="cancel"><span class="text_small">ou</span>
                    <a href="#" data-dismiss="modal" class="btn_cancelar">{% trans "Não" %}</a>
                </div>
            </div>
        {% endif %}
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        console.log("REMOVE!");
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        $('#btn_apagarSim').on("click", function () {

            var ids = new Array();
            console.log(ids)
            $('.values_delete').each(function () {
                ids.push($(this).val());
            });

            var target = "{%url 'subscriptions:delconfirme'%}"
            var csrftoken = getCookie('csrftoken');

            $('#apagarModal_atleta').modal('hide');

            $.ajax({
                type: "POST",
                url: target,
                data: {valores_list: ids},
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                },
                success: function (data) {
                    location.reload(true);//refresh na página
                    {#          		$('.form_id').html(data);#}
                    $('div').removeClass("modal-backdrop fade in");
                },
                error: function (rs, e) {

                }
            });
        });
    });


</script>